# Generated by Django 5.2.6 on 2025-09-08 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_remove_package_available_package_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='features',
        ),
    ]
