# Generated by Django 5.2.6 on 2025-09-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_remove_package_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='tier',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Bronze'), (2, 'Silver'), (3, 'Gold'), (4, 'Platinum')], default=1),
        ),
    ]
