# Generated by Django 5.2.6 on 2025-09-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_package_tier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['tier'], 'verbose_name': 'Package', 'verbose_name_plural': 'Packages'},
        ),
        migrations.AddField(
            model_name='package',
            name='intro',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
